AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Secure Chatbot Backend.

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - staging
      - production
    Description: "The environment where the stack will be deployed"
  OpenaiApiKey:
    Type: String
    Description: "OpenaiApiKey environment variable"
  BotpressToken:
    Type: String
    Description: "BotpressToken environment variable"
  BotpressEndpoint:
    Type: String
    Description: "BotpressEndpoint environment variable"

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x

Resources:
  SecureChatbotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "secure-chatbot-table-${Environment}"
      BillingMode: PROVISIONED
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "connectionId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: "connectionId-index"
          KeySchema:
            - AttributeName: "connectionId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  SecureChatbotReadScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: SecureChatbotTable
    Properties:
      MaxCapacity: 5
      MinCapacity: 1
      ResourceId: !Sub "table/secure-chatbot-table-${Environment}"
      ScalableDimension: "dynamodb:table:ReadCapacityUnits"
      ServiceNamespace: "dynamodb"
      RoleARN: !GetAtt AutoscalingRole.Arn

  SecureChatbotWriteScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: SecureChatbotTable
    Properties:
      MaxCapacity: 5
      MinCapacity: 1
      ResourceId: !Sub "table/secure-chatbot-table-${Environment}"
      ScalableDimension: "dynamodb:table:WriteCapacityUnits"
      ServiceNamespace: "dynamodb"
      RoleARN: !GetAtt AutoscalingRole.Arn

  SecureChatbotReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: SecureChatbotReadScalingTarget
    Properties:
      PolicyName: "SecureChatbotReadCapacityUtilization"
      PolicyType: "TargetTrackingScaling"
      ScalingTargetId: !Ref SecureChatbotReadScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        PredefinedMetricSpecification:
          PredefinedMetricType: "DynamoDBReadCapacityUtilization"

  SecureChatbotWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: SecureChatbotWriteScalingTarget
    Properties:
      PolicyName: "SecureChatbotWriteCapacityUtilization"
      PolicyType: "TargetTrackingScaling"
      ScalingTargetId: !Ref SecureChatbotWriteScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        PredefinedMetricSpecification:
          PredefinedMetricType: "DynamoDBWriteCapacityUtilization"

  AutoscalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "AutoscalingRole-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "application-autoscaling.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "DynamoDBAutoscalingPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:UpdateTable"
                  - "dynamodb:DescribeTable"
                Resource: "*"

  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SecureChatbotWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: !Ref Environment
      AutoDeploy: true

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "$connect"
      Target: !Join ["", ["integrations/", !Ref ConnectIntegration]]

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "$disconnect"
      Target: !Join ["", ["integrations/", !Ref DisconnectIntegration]]

  SendRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "send"
      Target: !Join ["", ["integrations/", !Ref SendIntegration]]

  UserSettingsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "userSettings"
      Target: !Join ["", ["integrations/", !Ref UserSettingsIntegration]]

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations
      PayloadFormatVersion: "1.0"

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations
      PayloadFormatVersion: "1.0"

  SendIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendMessageFunction.Arn}/invocations
      PayloadFormatVersion: "1.0"

  UserSettingsIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserSettingsFunction.Arn}/invocations
      PayloadFormatVersion: "1.0"

  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "OnConnectFunction-${Environment}"
      CodeUri: chatbot/onConnect/
      Handler: index.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SecureChatbotTable
      Events:
        WebSocket:
          Type: Api
          Properties:
            RestApiId: !Ref WebSocketApi
            Path: /$connect
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SecureChatbotTable

  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com

  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "OnDisconnectFunction-${Environment}"
      CodeUri: chatbot/onDisconnect/
      Handler: index.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SecureChatbotTable
      Events:
        WebSocket:
          Type: Api
          Properties:
            RestApiId: !Ref WebSocketApi
            Path: /$disconnect
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SecureChatbotTable

  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com

  SendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "SendMessageFunction-${Environment}"
      CodeUri: chatbot/sendMessage/
      Handler: index.handler
      Environment:
        Variables:
          ANONYMIZE_ENDPOINT: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/anonymize"
          BOTPRESS_TOKEN: !Ref BotpressToken
          BOTPRESS_ENDPOINT: !Ref BotpressEndpoint
      Events:
        WebSocket:
          Type: Api
          Properties:
            RestApiId: !Ref WebSocketApi
            Path: /send
            Method: post

  SendMessagePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SendMessageFunction
      Principal: apigateway.amazonaws.com

  UserSettingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "UserSettingsFunction-${Environment}"
      CodeUri: chatbot/userSettings/
      Handler: index.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SecureChatbotTable
      Events:
        WebSocket:
          Type: Api
          Properties:
            RestApiId: !Ref WebSocketApi
            Path: /userSettings
            Method: ANY

  UserSettingsPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UserSettingsFunction
      Principal: apigateway.amazonaws.com

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: AnonymizationServiceHttpApi

  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: !Ref Environment
      AutoDeploy: true

  AnonymizeMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "AnonymizeMessageFunction-${Environment}"
      CodeUri: anonymization-service/anonymizeMessage/
      Handler: index.handler
      Environment:
        Variables:
          LLM_LAMBDA_ENDPOINT: !GetAtt LlmStubFunctionUrl.FunctionUrl
          TABLE_NAME: !Ref SecureChatbotTable
          CALLBACK_URL: !Sub "https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
      Events:
        AnonymizeApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /anonymize
            Method: post
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SecureChatbotTable}"

  DeanonymizeMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "DeanonymizeMessageFunction-${Environment}"
      CodeUri: anonymization-service/deanonymizeMessage/
      Handler: index.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SecureChatbotTable
      Events:
        DeanonymizeApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /deanonymize
            Method: post
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SecureChatbotTable}"

  ForwardMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ForwardMessageFunction-${Environment}"
      CodeUri: chatbot/forwardMessage/
      Handler: index.handler
      Environment:
        Variables:
          DEANONYMIZE_ENDPOINT: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/deanonymize"
          TABLE_NAME: !Ref SecureChatbotTable
          CALLBACK_URL: !Sub "https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:Invoke
                - execute-api:ManageConnections
              Resource: arn:aws:execute-api:*:*:*
            - Effect: Allow
              Action:
                - dynamodb:*
                - dax:*
                - cloudwatch:*
                - datapipeline:*
                - ec2:DescribeVpcs
                - ec2:DescribeSubnets
                - ec2:DescribeSecurityGroups
                - iam:GetRole
                - iam:ListRoles
                - kms:DescribeKey
                - kms:ListAliases
                - sns:*
                - lambda:*
                - resource-groups:*
                - tag:GetResources
                - kinesis:*
              Resource: "*"
            - Effect: Allow
              Action: cloudwatch:GetInsightRuleReport
              Resource: arn:aws:cloudwatch:*:*:insight-rule/DynamoDBContributorInsights*
            - Effect: Allow
              Action: iam:PassRole
              Resource: "*"
              Condition:
                StringLike:
                  iam:PassedToService:
                    - application-autoscaling.amazonaws.com
                    - application-autoscaling.amazonaws.com.cn
                    - dax.amazonaws.com
            - Effect: Allow
              Action: iam:CreateServiceLinkedRole
              Resource: "*"
              Condition:
                StringEquals:
                  iam:AWSServiceName:
                    - replication.dynamodb.amazonaws.com
                    - dax.amazonaws.com
                    - dynamodb.application-autoscaling.amazonaws.com
                    - contributorinsights.dynamodb.amazonaws.com
                    - kinesisreplication.dynamodb.amazonaws.com
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"

  ForwardMessageFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt ForwardMessageFunction.Arn
      AuthType: NONE
      InvokeMode: BUFFERED
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST

  ForwardMessageFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ForwardMessageFunction.Arn
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

  LlmStubFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "LlmStubFunction-${Environment}"
      CodeUri: anonymization-service/llm-stub/
      Handler: index.handler
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenaiApiKey
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  LlmStubFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt LlmStubFunction.Arn
      AuthType: NONE
      InvokeMode: BUFFERED
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST

  LlmStubFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LlmStubFunction.Arn
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

Outputs:
  WebSocketApiEndpoint:
    Description: "Websocket API endpoint URL for real-time interactions"
    Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"

  HttpApiEndpoint:
    Description: "HTTP API endpoint URL for anonymization services"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"

  ForwardMessageUrl:
    Description: "Direct URL for ForwardMessage function"
    Value: !GetAtt ForwardMessageFunctionUrl.FunctionUrl

  LlmStubUrl:
    Description: "Direct URL for LLM-Stub function"
    Value: !GetAtt LlmStubFunctionUrl.FunctionUrl
